### ISSUE TITLE
WARNING: The following packages cannot be authenticated!

### ISSUE THREAD

**Issue by stylersnico** [uoi-io/ansible-galera#2]
Hi,

The playbook fail on Debian 8.5 with the following error message:

```bash
WARNING: The following packages cannot be authenticated! :  percona-toolkit percona-xtrabackup xtrabackup
```

You need to launch a apt-get update in your playbook before trying to install these packages.

**Comment by stylersnico** [comment]
Also:

```bash
failed: [46.101.190.144] (item=4567/tcp) => {"failed": true, "item": "4567/tcp", "msg": "firewalld and its python 2 module are required for this module"}
```

**Comment by goldyfruit** [comment]
@stylersnico about the firewalld issue it's because you have set the ``galera_firewalld: true`` without having the ``firewalld`` package install on your system.

About the warning you are completely right !

**Comment by goldyfruit** [comment]
Update the Readme to give more information about firewalld: https://github.com/uoi-io/ansible-galera/commit/4bf85fe0078b42e4fd0a5167355f67099fb344cf

Make sure the GPG key is installed before update the repository: https://github.com/uoi-io/ansible-galera/commit/d7091c29dd05eb89096755849b70bab6b4159e2d
